package View;
import Controller.Create_DB;

import javax.swing.*;
import java.awt.event.ActionEvent;
import javax.swing.table.DefaultTableModel;

public class AppointmentView extends javax.swing.JPanel {

    /**
     * Creates new form AppointmentView
     */
    public AppointmentView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        //added by CD
        dconn = new Create_DB();
        model = new DefaultTableModel();
        


        //netbeans info
        pageLabel = new javax.swing.JLabel();
        HcInput = new javax.swing.JTextField();
        pInfoLabel = new javax.swing.JLabel();
        docIDLabel = new javax.swing.JLabel();
        pNameLabel = new javax.swing.JLabel();
        HCNumLabel = new javax.swing.JLabel();
        pNameInput = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        docIdInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        yearLabel = new javax.swing.JLabel();
        yearDropInput = new javax.swing.JComboBox<>();
        step2LAbel = new javax.swing.JLabel();
        monthDropInput = new javax.swing.JComboBox<>();
        monthLabel = new javax.swing.JLabel();
        dayLabelInput = new javax.swing.JLabel();
        dayDropInput = new javax.swing.JComboBox<>();
        timeLabel = new javax.swing.JLabel();
        timeInput = new javax.swing.JComboBox<>();
        adminSsnInput = new javax.swing.JTextField();
        adminSsnLabel = new javax.swing.JLabel();
        drSSNInput = new javax.swing.JTextField();
        drSSNLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        hospitalNameLabel = new javax.swing.JLabel();
        hospitalNameInput = new javax.swing.JTextField();
        wardLabel = new javax.swing.JLabel();
        wardInput = new javax.swing.JTextField();
        roomLabel = new javax.swing.JLabel();
        roomInput = new javax.swing.JTextField();
        pNameLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        pNameLabel7 = new javax.swing.JLabel();
        pNameInput6 = new javax.swing.JTextField();
        finishButton = new javax.swing.JButton();
        createApptButton = new javax.swing.JButton();
        deleteApptButton = new javax.swing.JButton();
        updateApptButton = new javax.swing.JButton();

        pageLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pageLabel.setText("View/Change Appointments");

        pInfoLabel.setText("Patient Info");

        docIDLabel.setText("Document ID");

        pNameLabel.setText("Patient Name");

        HCNumLabel.setText("HC #");


        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "ConfirmationID", "Appt_Date", "Pname", "HealthCareNum", "Reason"
                }
        ));
        jTable.setModel(model);
        


        jScrollPane1.setViewportView(jTable);

        yearLabel.setText("Year");

        yearDropInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","1900","1901","1902","1903","1904"
        ,"1905","1906","1907","1908","1909","1910","1911","1912","1913","1914","1915","1916","1917","1918"
        ,"1919","1920","1921","1922","1923","1924","1925","1926","1927","1928","1929","1930","1931"
        ,"1932","1933","1934","1935","1936","1937","1938","1939","1940","1941","1942","1943","1944"
        ,"1945","1946","1947","1948","1949","1950","1951","1952","1953","1954","1955","1956","1957"
        ,"1958","1959","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970"
        ,"1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983"
        ,"1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996"
        ,"1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009"
        ,"2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","2023" }));

        step2LAbel.setText("Specify Appointment");

        monthDropInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","January", "February", "March"
        , "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        monthLabel.setText("Month");

        dayLabelInput.setText("Day");

        dayDropInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31" }));

        timeLabel.setText("Time");

        timeInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","8:00", "9:00", "10:00", "11:00", "12:00", "1:00", "2:00", "3:00", "4:00", "5:00", "6:00", "7:00" }));

        adminSsnLabel.setText("AdminSSN");

        drSSNLabel.setText("Doctor SSN");

        hospitalNameLabel.setText("Hospital Name");

        wardLabel.setText("Ward");

        roomLabel.setText("Room");

        pNameLabel6.setText("RoomType");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "General", "Operation", "Labratory"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        pNameLabel7.setText("Reason for Visit");

        finishButton.setText("Finished");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        createApptButton.setText("Create");
        createApptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createApptButtonActionPerformed(evt);
            }
        });

        deleteApptButton.setText("Delete");
        deleteApptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteApptButtonActionPerformed(evt);
            }
        });

        updateApptButton.setText("Update");
        updateApptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateApptButtonActionPerformed(evt);
            }
        });
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 57, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(74, 74, 74))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(backButton)
                                                .addGap(30, 30, 30)
                                                .addComponent(finishButton)
                                                .addGap(60, 60, 60))))
                        .addComponent(jSeparator1)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(416, 416, 416)
                                                .addComponent(pageLabel))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(adminSsnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(adminSsnLabel)
                                                        .addComponent(roomInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(roomLabel))
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(drSSNInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(drSSNLabel))
                                                                .addGap(28, 28, 28)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(hospitalNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(hospitalNameLabel))
                                                                .addGap(38, 38, 38)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(wardInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(wardLabel)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(pNameLabel6)
                                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(64, 64, 64)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(pNameLabel7)
                                                                        .addComponent(pNameInput6, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(step2LAbel)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(monthDropInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(22, 22, 22)
                                                                                .addComponent(monthLabel)))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(24, 24, 24)
                                                                                .addComponent(dayLabelInput))
                                                                        .addComponent(dayDropInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(yearDropInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(42, 42, 42)
                                                                                                .addComponent(yearLabel)))
                                                                                .addGap(42, 42, 42)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(timeLabel)
                                                                                        .addComponent(timeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(createApptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(49, 49, 49)
                                                                                .addComponent(updateApptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(49, 49, 49)
                                                                                .addComponent(deleteApptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(pNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(pNameLabel))
                                                                .addGap(35, 35, 35)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(HCNumLabel)
                                                                        .addComponent(HcInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(49, 49, 49)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(docIDLabel)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(docIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(50, 50, 50)
                                                                                .addComponent(searchButton))))
                                                        .addComponent(pInfoLabel))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(pageLabel)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(29, 29, 29)
                                                                .addComponent(adminSsnLabel)
                                                                .addGap(6, 6, 6)
                                                                .addComponent(adminSsnInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(hospitalNameLabel)
                                                                .addGap(6, 6, 6)
                                                                .addComponent(hospitalNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(drSSNLabel)
                                                .addGap(6, 6, 6)
                                                .addComponent(drSSNInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(wardLabel)
                                                .addGap(6, 6, 6)
                                                .addComponent(wardInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(roomLabel)
                                                        .addComponent(pNameLabel6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(roomInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(pNameLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pNameInput6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(pInfoLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pNameLabel)
                                        .addComponent(HCNumLabel)
                                        .addComponent(docIDLabel))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(HcInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(docIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(step2LAbel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(monthLabel)
                                                .addGap(4, 4, 4)
                                                .addComponent(monthDropInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(dayLabelInput)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dayDropInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(yearLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(yearDropInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(timeLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(timeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(createApptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(updateApptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(deleteApptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(backButton)
                                        .addComponent(finishButton))
                                .addGap(24, 24, 24))
        );
    }// </editor-fold>

    private void backButtonActionPerformed(ActionEvent evt) {
        MainView mainView = (MainView) SwingUtilities.getWindowAncestor(this);
        mainView.setRegisterPatientView(new RegisterPatientView());
        mainView.setCard(1);
    }

    private void updateApptButtonActionPerformed(ActionEvent evt) {


        if(docIdInput.getText() != ""){


        String monthToDigit = "01";

        if(monthDropInput.getSelectedItem() == "Janurary"){
                monthToDigit = "01";
        } else if (monthDropInput.getSelectedItem() == "February"){
                monthToDigit = "02";
        }else if (monthDropInput.getSelectedItem() == "March"){
                monthToDigit = "03";
        }else if (monthDropInput.getSelectedItem() == "April"){
                monthToDigit = "04";
        }else if (monthDropInput.getSelectedItem() == "May"){
                monthToDigit = "05";
        }else if (monthDropInput.getSelectedItem() == "June"){
                monthToDigit = "06";
        }else if (monthDropInput.getSelectedItem() == "July"){
                monthToDigit = "07";
        }else if (monthDropInput.getSelectedItem() == "August"){
                monthToDigit = "08";
        }else if (monthDropInput.getSelectedItem() == "September"){
                monthToDigit = "09";
        }
        else if (monthDropInput.getSelectedItem() == "October"){
                monthToDigit = "10";
        }
        else if (monthDropInput.getSelectedItem() == "November"){
                monthToDigit = "11";
        }
        else if (monthDropInput.getSelectedItem() == "December"){
                monthToDigit = "12";
        }else if (monthDropInput.getSelectedItem() == ""){
                monthToDigit = "";
        }

        String app_time = yearDropInput.getSelectedItem() + "-" + monthToDigit + "-" + dayDropInput.getSelectedItem() + " "+ timeInput.getSelectedItem() + ":00";

        if(yearDropInput.getSelectedItem().equals("") && yearDropInput.getSelectedItem().equals("") && yearDropInput.getSelectedItem().equals("")){
                app_time = "";
        }

        dconn.UpdateAppointment(hospitalNameInput.getText(),wardInput.getText(),roomInput.getText(),app_time,pNameInput6.getText(),docIdInput.getText());
        }else {
                JOptionPane.showMessageDialog(null, "Must have Document Number.");
        }
        // TODO add your handling code here:
    }

    private void deleteApptButtonActionPerformed(ActionEvent evt) {

        dconn.DeleteAppointment(docIdInput.getText());

    }

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {


        String appDate = yearDropInput.getSelectedItem() + "-" + monthDropInput.getSelectedItem() + "-" + dayDropInput.getSelectedItem() + " " + timeInput.getSelectedItem() + ":00" ;
        
        data = dconn.searchAppointment(pNameInput.getText(),HcInput.getText(),appDate, docIdInput.getText(), pNameInput6.getText());
        model.setDataVector(data, colNames);

        // TODO add your handling code here:
    }
    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {
        MainView mainView = (MainView) SwingUtilities.getWindowAncestor(this);
        mainView.setLoginView(new LoginView());
        mainView.setCard(0);
    }

    private void createApptButtonActionPerformed(java.awt.event.ActionEvent evt) {



        String monthToDigit = "01";

        if(monthDropInput.getSelectedItem() == "Janurary"){
                monthToDigit = "01";
        } else if (monthDropInput.getSelectedItem() == "February"){
                monthToDigit = "02";
        }else if (monthDropInput.getSelectedItem() == "March"){
                monthToDigit = "03";
        }else if (monthDropInput.getSelectedItem() == "April"){
                monthToDigit = "04";
        }else if (monthDropInput.getSelectedItem() == "May"){
                monthToDigit = "05";
        }else if (monthDropInput.getSelectedItem() == "June"){
                monthToDigit = "06";
        }else if (monthDropInput.getSelectedItem() == "July"){
                monthToDigit = "07";
        }else if (monthDropInput.getSelectedItem() == "August"){
                monthToDigit = "08";
        }else if (monthDropInput.getSelectedItem() == "September"){
                monthToDigit = "09";
        }
        else if (monthDropInput.getSelectedItem() == "October"){
                monthToDigit = "10";
        }
        else if (monthDropInput.getSelectedItem() == "November"){
                monthToDigit = "11";
        }
        else if (monthDropInput.getSelectedItem() == "December"){
                monthToDigit = "12";
        }else if (monthDropInput.getSelectedItem() == ""){
                monthToDigit = "";
        }

        String app_time = yearDropInput.getSelectedItem() + "-" + monthToDigit + "-" + dayDropInput.getSelectedItem() + " "+ timeInput.getSelectedItem() + ":00";






        if (adminSsnInput.getText().equals("") || drSSNInput.getText().equals("") || hospitalNameInput.getText().equals("") || wardInput.getText().equals("") || roomInput.getText().equals("") || HcInput.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Must enter name, healthcare number, smoker status and gender.");
            } else {
                dconn.InsertAppointment(docIdInput.getText(), drSSNInput.getText(), adminSsnInput.getText(), hospitalNameInput.getText(), wardInput.getText(), roomInput.getText(),jList1.getSelectedValue(),app_time,pNameInput6.getText());
            }


        // TODO add your handling code here:

        
    }


    // Variables declaration - do not modify
    private javax.swing.JLabel HCNumLabel;
    private javax.swing.JTextField HcInput;
    private javax.swing.JTextField adminSsnInput;
    private javax.swing.JLabel adminSsnLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JButton createApptButton;
    private javax.swing.JComboBox<String> dayDropInput;
    private javax.swing.JLabel dayLabelInput;
    private javax.swing.JButton deleteApptButton;
    private javax.swing.JLabel docIDLabel;
    private javax.swing.JTextField docIdInput;
    private javax.swing.JTextField drSSNInput;
    private javax.swing.JLabel drSSNLabel;
    private javax.swing.JButton finishButton;
    private javax.swing.JTextField hospitalNameInput;
    private javax.swing.JLabel hospitalNameLabel;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable;
    private javax.swing.JComboBox<String> monthDropInput;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JLabel pInfoLabel;
    private javax.swing.JTextField pNameInput;
    private javax.swing.JTextField pNameInput6;
    private javax.swing.JLabel pNameLabel;
    private javax.swing.JLabel pNameLabel6;
    private javax.swing.JLabel pNameLabel7;
    private javax.swing.JLabel pageLabel;
    private javax.swing.JTextField roomInput;
    private javax.swing.JLabel roomLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel step2LAbel;
    private javax.swing.JComboBox<String> timeInput;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JButton updateApptButton;
    private javax.swing.JTextField wardInput;
    private javax.swing.JLabel wardLabel;
    private javax.swing.JComboBox<String> yearDropInput;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration


    //Added by CD
    private Create_DB dconn;
    private Object[][] data;
    private DefaultTableModel model;
    private String[] colNames = {"ConfirmationID","Hospital", "Ward","RoomNo","Appt_Date", "Pname", "HealthCareNum", "Reason"};

}

