package View;

import javax.swing.*;
import java.awt.event.ActionEvent;

public class LabTechView extends javax.swing.JPanel {

    /**
     * Creates new form LabTechView
     */
    public LabTechView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void initComponents() {

        pageLabel2 = new javax.swing.JLabel();
        HcnInput = new javax.swing.JTextField();
        HCNumLabel = new javax.swing.JLabel();
        testTypeInput = new javax.swing.JTextField();
        testTypeLabel = new javax.swing.JLabel();
        resultsInput = new javax.swing.JTextField();
        resultsLabel = new javax.swing.JLabel();
        docIDInput = new javax.swing.JTextField();
        docIDLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        resultsTable = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        searchResultsLabel = new javax.swing.JLabel();
        labReqLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pageLabel1 = new javax.swing.JLabel();
        updateLabButton = new javax.swing.JButton();
        successLabel = new javax.swing.JLabel();

        pageLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pageLabel2.setText("Update Lab Results");

        HCNumLabel.setText("HC #");

        testTypeLabel.setText("Test Type");

        resultsLabel.setText("Results");

        docIDLabel.setText("DocumentID");

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        resultsTable.setViewportView(jTable);

        searchResultsLabel.setText("Search Results");

        labReqLabel.setText("Search for Lab Requisition");

        pageLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pageLabel1.setText("Lab Tech Page");

        updateLabButton.setText("Update");
        updateLabButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLabButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGap(41, 41, 41)
                                .addComponent(exitButton)
                                .addGap(28, 28, 28))
                        .addComponent(jSeparator1)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(95, 95, 95)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(HCNumLabel)
                                                                        .addComponent(HcnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(labReqLabel))
                                                                .addGap(53, 53, 53)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(docIDLabel)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(docIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(114, 114, 114)
                                                                                .addComponent(searchButton))))
                                                        .addComponent(resultsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(searchResultsLabel)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(421, 421, 421)
                                                .addComponent(pageLabel2))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(97, 97, 97)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(testTypeLabel)
                                                        .addComponent(testTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(resultsLabel)
                                                        .addComponent(resultsInput, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(updateLabButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(successLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(102, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(432, 432, 432)
                                        .addComponent(pageLabel1)
                                        .addContainerGap(455, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(73, Short.MAX_VALUE)
                                .addComponent(labReqLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(HCNumLabel)
                                                .addGap(6, 6, 6)
                                                .addComponent(HcnInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(docIDLabel)
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(docIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(searchButton))))
                                .addGap(45, 45, 45)
                                .addComponent(searchResultsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(exitButton))
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(pageLabel2)
                                                .addGap(29, 29, 29)
                                                .addComponent(testTypeLabel)
                                                .addGap(6, 6, 6)
                                                .addComponent(testTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(52, 52, 52)
                                                .addComponent(resultsLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(resultsInput, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(updateLabButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(successLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(23, 23, 23))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(pageLabel1)
                                        .addContainerGap(902, Short.MAX_VALUE)))
        );
    }// </editor-fold>

    private void updateLabButtonActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:

        successLabel.setText("Test results updated successfully");
    }

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        MainView mainView = (MainView) SwingUtilities.getWindowAncestor(this);
        mainView.setLoginView(new LoginView());
        mainView.setCard(0);
    }

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify                     
    private javax.swing.JLabel HCNumLabel;
    private javax.swing.JTextField HcnInput;
    private javax.swing.JTextField docIDInput;
    private javax.swing.JLabel docIDLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel labReqLabel;
    private javax.swing.JLabel pageLabel1;
    private javax.swing.JLabel pageLabel2;
    private javax.swing.JTextField resultsInput;
    private javax.swing.JLabel resultsLabel;
    private javax.swing.JScrollPane resultsTable;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchResultsLabel;
    private javax.swing.JLabel successLabel;
    private javax.swing.JTextField testTypeInput;
    private javax.swing.JLabel testTypeLabel;
    private javax.swing.JButton updateLabButton;
    // End of variables declaration                   
}
