package View;

import javax.swing.*;
import java.awt.*;

public class PatientView extends javax.swing.JPanel {

    /**
     * Creates new form PatientView
     */
    public PatientView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        EnterHcnLabel = new javax.swing.JLabel();
        HcnInput = new javax.swing.JTextField();
        DateInput = new javax.swing.JLabel();
        monthDrop = new javax.swing.JComboBox<>();
        monthLabel = new javax.swing.JLabel();
        dayLabel = new javax.swing.JLabel();
        dayDrop = new javax.swing.JComboBox<>();
        yearLabel = new javax.swing.JLabel();
        yearDrop = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();
        successFailurebox = new javax.swing.JScrollPane();
        confirmTextBox = new javax.swing.JTextPane();
        finishButton = new javax.swing.JButton();

        EnterHcnLabel.setText("Step 1: Enter your Health Card Number (example 123-345-678)");

        HcnInput.setText("Health Card Number");
        HcnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HcnInputActionPerformed(evt);
            }
        });

        DateInput.setText("Step 2: Select the date of your desired appointment");

        monthDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March",
                "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        monthLabel.setText("Month");

        dayLabel.setText("Day");

        dayDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8",
                "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24",
                "25", "26", "27", "28", "29", "30", "31" }));

        yearLabel.setText("Year");

        yearDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024" }));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        successFailurebox.setViewportView(confirmTextBox);

        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(DateInput)
                                                        .addGap(31, 31, 31))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(15, 15, 15)
                                                                        .addComponent(monthLabel))
                                                                .addComponent(monthDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(43, 43, 43)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(15, 15, 15)
                                                                        .addComponent(dayLabel)
                                                                        .addGap(50, 50, 50)
                                                                        .addComponent(yearLabel))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(dayDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(44, 44, 44)
                                                                        .addComponent(yearDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(submitButton)
                                                        .addGap(116, 116, 116))
                                                .addComponent(successFailurebox, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(HcnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EnterHcnLabel))
                                .addContainerGap(95, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(finishButton)
                                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(EnterHcnLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HcnInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DateInput)
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(monthLabel)
                                        .addComponent(dayLabel)
                                        .addComponent(yearLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(monthDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dayDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(yearDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(submitButton)
                                .addGap(33, 33, 33)
                                .addComponent(successFailurebox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                                .addComponent(finishButton)
                                .addGap(17, 17, 17))
        );
    }// </editor-fold>

    private void HcnInputActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify
    private javax.swing.JLabel DateInput;
    private javax.swing.JLabel EnterHcnLabel;
    private javax.swing.JTextField HcnInput;
    private javax.swing.JTextPane confirmTextBox;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JButton finishButton;
    private javax.swing.JComboBox<String> monthDrop;
    private javax.swing.JComboBox<String> dayDrop;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JScrollPane successFailurebox;
    private javax.swing.JComboBox<String> yearDrop;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration
}